{{- if .Values.backstage.appEnvSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.appEnvSecretsName" . }}
  namespace: {{ .Release.Namespace | quote }}
stringData:
    {{- include "common.tplvalues.render" ( dict "value" .Values.backstage.appEnvSecrets "context" $) | nindent 4 }}
type: Opaque
{{- end }}
