{{- if .Values.global.cp }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.tibcoEnvSecretsName" . }}
  namespace: {{ .Release.Namespace | quote }}
stringData:
    authClientId: {{ .Values.global.cp.clientId }}
    authClientSecret: {{ .Values.global.cp.clientSecret }}
type: Opaque
{{- end }}
