{{- if .Values.global.cp }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.tibcoEnvSecretsName" . }}
  namespace: {{ .Release.Namespace | quote }}
string:
    authClientId: {{ .Values.global.cp.clientId | b64enc }}
    {{- /* client secret is already encoded */}}
    authClientSecret: {{ .Values.global.secrets.clientSecret }}
type: Opaque
{{- end }}
